// Firebase configuration - Auto-generated from environment variables
// DO NOT EDIT THIS FILE MANUALLY - Run: node setup-firebase.js
// Or set via extension popup settings

// This will be populated by setup-firebase.js from environment variables
// Or you can manually set it here for testing
const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_PROJECT_ID.firebaseapp.com",
  databaseURL: "https://YOUR_PROJECT_ID-default-rtdb.firebaseio.com/",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_PROJECT_ID.appspot.com",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID"
};
